# (from:http://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html)

language: scala
scala:
   - 2.11.12

script:
  # sbt stage
  - sbt stage
  # NOTE: This is just a working-test
  - ./target/universal/stage/bin/wikipedia-dump-loader-example-scala

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/